### ISSUE TITLE
Expanding hosting scope

### ISSUE THREAD

**Issue by laggycomputer** [IngeniousCoder/MakeMeOnline#2]
I'd like to point out that using Heroku is unnecessary here, and I would say is a worse idea than just simply hosting at home.

Heroku is very unlikely to work with ANY C bindings (`pynacl`, `libsodium`, `lxml`). Voice support for Heroku is nonexistent. On Heroku, your free hosting hours are limited on a per-month basis, as well as control of your application. Your bot is restarted once per 24 hours and is discarded every time your application crashes.

Saying that such values need to be Heroku config variables is VERY misleading. They are simply environment variables that can be set in any local shell.

Since this is the case, I'd recommend changing the name of these variables to something along the lines of `superselfbot_VARNAME` to avoid conflicts with other projects (namely Discord bots) that use similar environment variable names.

**Comment by IngeniousCoder** [comment]
Thank you for your wonderful suggestion! I have fixed and changed it.

**Comment by laggycomputer** [comment]
You may want to update `README` too.

**Comment by IngeniousCoder** [comment]
I did, thanks :)
